### ISSUE TITLE
Not possible to specify curl options

### ISSUE THREAD

**Issue by rattuscz** [Kdyby/ElasticSearch#10]
elastica client expects curl options as key => value directly put into curl_setopt :

```
foreach ($this->getConnection()->getConfig('curl') as $key => $param) {
                curl_setopt($curlConnection, $key, $param);
}
```

This is not possible as keys are CURLOPT_\* constants which are integer and Config::merge helper reindexes arrays with integer keys:
DI builder users Config\Helpers::merge to build configuration array :
https://github.com/Kdyby/ElasticSearch/blob/master/src/Kdyby/ElasticSearch/DI/SearchExtension.php#L69
Helpers::merge reindexes array if keys are integers : 
https://github.com/nette/di/blob/master/src/DI/Config/Helpers.php#L28-L29

Secondary issue is that just putting those constants in config is pain because ::constant(...) is not valid array key in neon syntax.

Therefore I would love to have option of using string constants, possibly same as in Kdyby/Curl - using just part after CURLOPT_ : `$constant = 'CURLOPT_' . strtoupper($option)` which would be processed in during config build to correct array of parameters for elastica

**Comment by fprochazka** [comment]
Thank you for the pull! :)
