### ISSUE TITLE
New release of ruflin/Elastica is available

### ISSUE THREAD

**Issue by jannovy** [Kdyby/ElasticSearch#15]
Current version in composer.json (~2.1.0) of Elastica does not support ElasticSearch 2.2.0 Is possible to make a new release of Kdyby/ElasticSearch with dependency to 3.1.0 ?

https://github.com/ruflin/Elastica/releases/tag/3.1.0

**Comment by fprochazka** [comment]
Sure :+1:

**Comment by publicfun** [comment]
:+1:

**Comment by janharsa** [comment]
I vote for this update 👍

**Comment by Buri** [comment]
+1 for update

**Comment by martinjinda** [comment]
I'm getting following error: `Compile Error Cannot use Elastica\Filter\Bool as Bool because is a special class name` and this plugin doesn't work from at all. Is there some workaround?

**Comment by Buri** [comment]
You can try `use Elastica\Filter\Bool as EBool;`

**Comment by dakorpar** [comment]
Only version 5 and 6 are now supported.
